/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Exercise detail sheet (rebuild to exercise-detail.html). Form content binds
 * to the curated Exercise dataset only, never generated by a model at runtime.
 * "Why this works" and "Watch out for" are authored editorial slots; until the
 * dataset ships them they show a plain "details coming soon" state, never fake
 * cues. See exercise-detail-claude-code-prompt.md + project data model.
 */
import React, { useState, useEffect } from "react";
import { Exercise } from "../types";
import { motion, AnimatePresence, useReducedMotion, useDragControls } from "motion/react";
import { Button } from "./ui/Button";
import { useBackHandler } from "../lib/backStack";
import { exerciseScience } from "../data/exerciseScience";

// Register helper for dispatching global events
export function openExerciseGuide(exercise: Exercise) {
  window.dispatchEvent(new CustomEvent("open-exercise-guide", { detail: exercise }));
}

// Extract a YouTube id from various link styles
function getYouTubeEmbedId(url?: string): string | null {
  if (!url) return null;
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);
  return match && match[2].length === 11 ? match[2] : null;
}

// A comma / newline / JSON-array list field -> string[]
function parseList(v?: string | string[]): string[] {
  if (!v) return [];
  if (Array.isArray(v)) return v.filter(Boolean);
  try {
    const p = JSON.parse(v);
    if (Array.isArray(p)) return p.filter(Boolean);
  } catch {
    /* not JSON */
  }
  return v.split(",").map((s) => s.trim()).filter(Boolean);
}

// setupInstructions + formMechanics -> numbered steps; legacy correctForm blob
// is the prose fallback until structured steps are filled.
function deriveSteps(ex: Exercise): { steps: string[] | null; prose: string | null } {
  const lines = (t?: string) =>
    t ? t.split(/\n+/).map((s) => s.trim().replace(/^\d+[.\)]\s*/, "").replace(/^[•\-]\s*/, "")).filter(Boolean) : [];
  const combined = [...lines(ex.setupInstructions), ...lines(ex.formMechanics)];
  if (combined.length > 0) return { steps: combined, prose: null };
  if (ex.correctForm && ex.correctForm.trim()) return { steps: null, prose: ex.correctForm.trim() };
  return { steps: null, prose: null };
}

// Coarse front figure. The exercise's category region shades violet, the rest
// of the body is drawn in the theme's on-colour (currentColor) at low alpha so
// it reads in dark and light. Only the violet intensity is a literal.
const REGION_BY_CAT: Record<string, string[]> = {
  Chest: ["chest"],
  Back: ["shoulders", "arms"],
  Legs: ["legs"],
  Shoulders: ["shoulders"],
  Arms: ["arms"],
  Core: ["core"],
  Cardio: ["legs", "core"],
};

function BodyFigure({ category }: { category: string }) {
  const hi = REGION_BY_CAT[category] || [];
  const fill = (r: string) => (hi.includes(r) ? "#9a6cff" : "currentColor");
  const op = (r: string) => (hi.includes(r) ? 1 : 0.06);
  return (
    <svg viewBox="0 0 200 300" width="96" style={{ color: "var(--m3-on)", display: "block" }}>
      <g stroke="currentColor" strokeOpacity={0.12} strokeWidth={1.5}>
        <circle cx="100" cy="30" r="15" fill="currentColor" fillOpacity={0.06} />
        <rect x="92" y="44" width="16" height="11" rx="5" fill="currentColor" fillOpacity={0.06} />
        <ellipse cx="70" cy="74" rx="16" ry="12" fill={fill("shoulders")} fillOpacity={op("shoulders")} />
        <ellipse cx="130" cy="74" rx="16" ry="12" fill={fill("shoulders")} fillOpacity={op("shoulders")} />
        <rect x="76" y="66" width="24" height="10" rx="5" fill={fill("chest")} fillOpacity={op("chest")} />
        <rect x="100" y="66" width="24" height="10" rx="5" fill={fill("chest")} fillOpacity={op("chest")} />
        <rect x="76" y="78" width="24" height="11" rx="5" fill={fill("chest")} fillOpacity={op("chest")} />
        <rect x="100" y="78" width="24" height="11" rx="5" fill={fill("chest")} fillOpacity={op("chest")} />
        <rect x="60" y="84" width="16" height="42" rx="8" fill={fill("arms")} fillOpacity={op("arms")} />
        <rect x="124" y="84" width="16" height="42" rx="8" fill={fill("arms")} fillOpacity={op("arms")} />
        <rect x="84" y="96" width="32" height="48" rx="10" fill={fill("core")} fillOpacity={op("core")} />
        <rect x="82" y="150" width="16" height="60" rx="8" fill={fill("legs")} fillOpacity={op("legs")} />
        <rect x="102" y="150" width="16" height="60" rx="8" fill={fill("legs")} fillOpacity={op("legs")} />
      </g>
    </svg>
  );
}

export default function ExerciseGuideModal() {
  const [open, setOpen] = useState(false);
  const [exercise, setExercise] = useState<Exercise | null>(null);
  const reduce = useReducedMotion();
  useBackHandler(open, () => setOpen(false)); // (o4) back closes the guide sheet
  const dragControls = useDragControls();

  useEffect(() => {
    const handleOpen = (e: Event) => {
      const ce = e as CustomEvent<Exercise>;
      if (ce.detail) {
        setExercise(ce.detail);
        setOpen(true);
      }
    };
    window.addEventListener("open-exercise-guide", handleOpen);
    return () => window.removeEventListener("open-exercise-guide", handleOpen);
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    if (open) {
      window.addEventListener("keydown", onKey);
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [open]);

  const close = () => setOpen(false);

  const ex = exercise;
  const { steps, prose } = ex ? deriveSteps(ex) : { steps: null, prose: null };
  const primary = ex ? (parseList(ex.primaryTarget).length ? parseList(ex.primaryTarget) : [ex.category]) : [];
  const secondary = ex ? parseList(ex.secondaryTarget) : [];
  const science = ex ? exerciseScience[ex.id] : undefined; // authored "why" + "watch out"
  const ytId = ex ? getYouTubeEmbedId(ex.videoLink) : null;

  return (
    <AnimatePresence>
      {open && ex && (
        <motion.div
          className="fixed inset-0 z-[110] flex items-end justify-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          style={{ background: "rgba(0,0,0,.6)", backdropFilter: "blur(6px)", WebkitBackdropFilter: "blur(6px)" }}
          onClick={close}
        >
          <motion.div
            className="pbw-edsheet"
            onClick={(e) => e.stopPropagation()}
            initial={reduce ? false : { y: "100%" }}
            animate={{ y: 0 }}
            exit={reduce ? { opacity: 0 } : { y: "100%" }}
            transition={{ type: "spring", stiffness: 320, damping: 34 }}
            drag={reduce ? false : "y"}
            dragListener={false}
            dragControls={dragControls}
            dragConstraints={{ top: 0, bottom: 0 }}
            dragElastic={{ top: 0, bottom: 0.5 }}
            onDragEnd={(_e, info) => {
              if (info.offset.y > 120) close();
            }}
          >
            <div
              className="handle"
              onPointerDown={(e) => !reduce && dragControls.start(e)}
              style={{ touchAction: "none" }}
            />
            <button className="sclose" onClick={close} aria-label="Close">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d="M6 6l12 12M18 6L6 18" /></svg>
            </button>

            <div className="exhd">
              <div className="chips">
                <span className="cat">{ex.category}</span>
                <span className="dot">·</span>
                <span className="cat">{ex.equipment}</span>
              </div>
              <div className="exname">{ex.name}</div>
            </div>

            <div className="sheetbody">
              {/* Looping demo */}
              <div className="demo">
                <div className="demoframe">
                  {ex.mediaUrl && ex.mediaType === "image" ? (
                    <img src={ex.mediaUrl} alt={`${ex.name} demo`} referrerPolicy="no-referrer" />
                  ) : ex.mediaUrl && ex.mediaType === "video" ? (
                    <video src={ex.mediaUrl} autoPlay loop muted playsInline />
                  ) : ytId ? (
                    <img src={`https://img.youtube.com/vi/${ytId}/hqdefault.jpg`} alt={`${ex.name} demo`} referrerPolicy="no-referrer" />
                  ) : (
                    <span className="demoplay">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d="M8 5v14l11-7z" fill="currentColor" stroke="none" /></svg>
                    </span>
                  )}
                </div>
                <span className="demotag">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d="M17 2l4 4-4 4" /><path d="M3 11V9a4 4 0 0 1 4-4h14M7 22l-4-4 4-4" /><path d="M21 13v2a4 4 0 0 1-4 4H3" /></svg>
                  Looping demo
                </span>
              </div>

              {/* How to do it */}
              <div className="sec">How to do it</div>
              <div className="card steps">
                {steps ? (
                  steps.map((s, i) => (
                    <div key={i} className="step">
                      <span className="sn">{i + 1}</span>
                      <p>{s}</p>
                    </div>
                  ))
                ) : prose ? (
                  <p className="cardprose">{prose}</p>
                ) : (
                  <p className="pbw-edempty">Step-by-step instructions for this exercise are coming soon.</p>
                )}
              </div>

              {/* Why this works */}
              <div className="whycard">
                <div className="whyhd">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d="M9 18h6M10 22h4M12 2a7 7 0 0 0-4 12.7c.6.5 1 1.3 1 2.1V18h6v-1.2c0-.8.4-1.6 1-2.1A7 7 0 0 0 12 2z" /></svg>
                  <span>Why this works</span>
                </div>
                <p>{science?.why ? science.why : (ex.coachTip && ex.coachTip.trim() ? ex.coachTip.trim() : "The coaching write-up for this exercise is coming soon.")}</p>
              </div>

              {/* Muscles worked */}
              <div className="sec">Muscles worked</div>
              <div className="card muscle">
                <div className="figwrap"><BodyFigure category={ex.category} /></div>
                <div className="mcols">
                  <div className="mcol">
                    <div className="mlab">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9" /><circle cx="12" cy="12" r="5" /><circle cx="12" cy="12" r="1.5" fill="currentColor" stroke="none" /></svg>
                      Primary
                    </div>
                    <div className="mrow">
                      {primary.map((m, i) => (
                        <span key={i} className="mchip p">{m}</span>
                      ))}
                    </div>
                  </div>
                  {secondary.length > 0 && (
                    <div className="mcol">
                      <div className="mlab">Secondary</div>
                      <div className="mrow">
                        {secondary.map((m, i) => (
                          <span key={i} className="mchip">{m}</span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Watch out for */}
              <div className="sec">Watch out for</div>
              <div className="card misscard">
                {science?.watchOut
                  ? <p>{science.watchOut}</p>
                  : <p className="pbw-edempty">Common mistakes for this exercise are coming soon.</p>}
              </div>

              <Button variant="none" className="gotit" onClick={close}>Got it</Button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
